# Generated by Django 5.2.4 on 2025-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='university',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='faculties'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
