# Generated by Django 5.2.4 on 2025-08-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_remove_faculty_university_alter_faculty_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
