# Generated by Django 5.2.4 on 2025-08-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_faculty_name_alter_faculty_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='logo',
            field=models.ImageField(upload_to='faculties'),
        ),
    ]
