# Generated by Django 5.2.4 on 2025-08-16 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_faculty_logo'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='university.university'),
            preserve_default=False,
        ),
    ]
