# Generated by Django 5.2.4 on 2025-08-12 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_alter_lecture_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(null=True, related_name='lectures', to=settings.AUTH_USER_MODEL),
        ),
    ]
