# Generated by Django 5.2.4 on 2025-08-16 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('lecture', '0003_alter_lecture_students'),
        ('location', '0002_location_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='title',
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='location.location'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(related_name='lectures_attended', to=settings.AUTH_USER_MODEL),
        ),
    ]
