# Generated by Django 5.2.4 on 2025-08-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('logo', models.ImageField(upload_to='universities')),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
    ]
