# Generated by Django 5.2.4 on 2025-08-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
